CREATE DATABASE mutantes
    WITH
    OWNER = useradn
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

CREATE ROLE useradn WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:lBQMfOWPjuLZFAaDSF8bCg==$9klyORvoxEvFzeOijYdwrvqAafd0L+HijghCiuG2hok=:IamduZNYCvohHOahka9O5ZQ3KzQ2fWf5jxkB4VqEQLQ=';